"""empty message

Revision ID: 3a917ca73882
Revises: 88d8f8ba14e6
Create Date: 2023-10-12 20:17:38.288179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a917ca73882'
down_revision = '88d8f8ba14e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=255), nullable=True),
    sa.Column('name2', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.Text(), nullable=True),
    sa.Column('city2', sa.String(length=255), nullable=True),
    sa.Column('country2', sa.String(length=255), nullable=True),
    sa.Column('state2', sa.String(length=255), nullable=True),
    sa.Column('zip_code2', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address_book')
    # ### end Alembic commands ###
